### ISSUE TITLE
last and not_last do not seem to work

### ISSUE THREAD

**Issue by cortlandstarrett** [xtuml/pyrsl#2]
I am iterating through a set.  not_last is always true.  last is always false.

**Comment by john-tornblom** [comment]
The type checking of the operator may need some better error messages, if the operand is not a set, it is always false. So might be you have the wrong operand. This seems to work as expected:

.select many o_objs from instances of O_OBJ
.for each o_obj in o_objs
  .assign is_last = (last o_objs)
  .assign is_not_last = (not_last o_objs)
  .print "is_last: ${is_last}"
  .print "is_not_last: ${is_not_last}"
.end for

**Comment by cortlandstarrett** [comment]
The case where I saw this failure had a large amount of intervening code between the beginning of the for statement and the test for last.  I will need to selectively remove code from this middle body until I see a behavior change.

**Comment by keithbrown** [comment]
I just debugged some build failures building BridgePoint with MC-Java down to an issue with `(not_)[last | first]` operators.  

I'm pretty sure I can see why.  See https://github.com/xtuml/pyrsl/blob/master/rsl/eval.py#L326

I note that Cort said previously in his bug report "there is a lot of intervening code".  Mine has some as well.... including `.select` statements.  I think pyrsl is using the `selected` keyword invalidly.  Our intervening code is overwriting `selected` and messing up the aforementioned eval statements in pyrsl.

If my hypothesis is correct, I think pyrsl must be fixed. It's completely wrong for the test operators to fail due to an intermediate `.select` inside the loop.

Here's an example of where I see a failure: https://github.com/xtuml/bridgepoint/blob/master/src/MC-Java/java.arc#L1149

The loop starts on 1131 and there are several `.select`s inside it.

**Comment by keithbrown** [comment]
I also believe that the `test_[last, first, not_last, not_first]_in_loop` functions in `pyrsl/test/test_loop.py` are invalid.
- They do not truly test for first, last, etc. because they are not checking an attribute of the instances, they are simply looping and counting.
- The invalidity is evident by noticing the fact that the first/last and not_first/not_last test operations work identically.
- The loop and count method of test does not prove that the correct element (first or last) was the one skipped.
- To test properly, one would need to declare and attribute on test class "A", named something like `integer ID`.  The test for `not_first` should work like this pseudo-code:

```
// assign values to all 10 instances of A.
A.ID = {42, 0, 0, 0, 0, 0, 0, 0, 0, 0}
.select many a_set from instances of A
.assign x = 0;
.for each a in a_set
  .if (not_first a_set)
    .assign x = x + a.ID
  .end if
.end for
.exit x

// return value of the loop should be 0
```

The test for `first` should work like this pseudo-code:

```
// assign values to all 10 instances of A.
A.ID = {42, 1, 1, 1, 1, 1, 1, 1, 1, 1}
.select many a_set from instances of A
.assign x = 0;
.for each a in a_set
  .if (first a_set)
    .assign x = x + a.ID
  .end if
.end for
.exit x

// return value of the loop should be 42
```

I do note that even with this improvement, the failure noted in my previous comment induced by an intermediate `.select` inside the for loop is not specifically tested.

**Comment by keithbrown** [comment]
I believe I found a simple fix for the bug.  I made the change and will test. 

See https://github.com/keithbrown/pyrsl/commit/c5531d18a42d09b85db6973697e35414df08774a

There is a name collision.  Because "where ..." also installs the symbol "selected" (https://github.com/keithbrown/pyrsl/blob/c5531d18a42d09b85db6973697e35414df08774a/rsl/eval.py#L469)

So `select ... where` inside the for loop collides.

It appears there may still be scoping issues if uses of first/last are nested.

**Comment by keithbrown** [comment]
The simple fix I referenced in the previous comment worked for me while building bp.core.

**Comment by keithbrown** [comment]
Updated tests/test_loop.py in branch 8442_build_bp_pyrsl to test the (not_)[first | last] operators as I suggested in an earlier comment.

**Comment by john-tornblom** [comment]
It might be that symbols are accessed in the wrong order. Could you try this patch instead: https://github.com/john-tornblom/pyrsl/commit/871db50422c1cb71416fd3fbde9b9bc5bc328703

Also, i think the approach of reaming the symbols from selected to instselected or whatever may cause collisions with variables. If anything, prefix wih _. but the above patch should work without renaming selected.

**Comment by john-tornblom** [comment]
never mind, it is still not fixed. But I'll give it another go during the weekend. I got some ideas.

**Comment by john-tornblom** [comment]
I think this might fix it https://github.com/john-tornblom/pyrsl/commit/8b7a2171f0ba329143289d98da8653ea889c0b7e

**Comment by keithbrown** [comment]
I merged the 8b7a217 change into my development branch.  I see these test failures:

```
======================================================================
ERROR: test_parameter_named_cardinality (test_invoke.TestInvoke)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kbrown/git/pyrsl/tests/utils.py", line 36, in <lambda>
    f.__module__ + '.' + f.__name__))
  File "/home/kbrown/git/pyrsl/tests/utils.py", line 21, in eval_text
    ast = rsl.parse_text(text + '\n', filename)
  File "/home/kbrown/git/pyrsl/rsl/parse.py", line 1456, in parse_text
    return parser.text_input(text, filename)
  File "/home/kbrown/git/pyrsl/rsl/parse.py", line 153, in text_input
    tracking=1)
  File "/usr/lib/python2.7/dist-packages/ply/yacc.py", line 267, in parse
    return self.parseopt(input,lexer,debug,tracking,tokenfunc)
  File "/usr/lib/python2.7/dist-packages/ply/yacc.py", line 796, in parseopt
    tok = self.errorfunc(errtoken)
  File "/home/kbrown/git/pyrsl/rsl/parse.py", line 1443, in p_error
    p.lineno))
ParseException: invalid token 'UOP' at test_invoke.test_parameter_named_cardinality:3

======================================================================
ERROR: test_parameter_named_from (test_invoke.TestInvoke)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kbrown/git/pyrsl/tests/utils.py", line 36, in <lambda>
    f.__module__ + '.' + f.__name__))
  File "/home/kbrown/git/pyrsl/tests/utils.py", line 21, in eval_text
    ast = rsl.parse_text(text + '\n', filename)
  File "/home/kbrown/git/pyrsl/rsl/parse.py", line 1456, in parse_text
    return parser.text_input(text, filename)
  File "/home/kbrown/git/pyrsl/rsl/parse.py", line 153, in text_input
    tracking=1)
  File "/usr/lib/python2.7/dist-packages/ply/yacc.py", line 267, in parse
    return self.parseopt(input,lexer,debug,tracking,tokenfunc)
  File "/usr/lib/python2.7/dist-packages/ply/yacc.py", line 796, in parseopt
    tok = self.errorfunc(errtoken)
  File "/home/kbrown/git/pyrsl/rsl/parse.py", line 1443, in p_error
    p.lineno))
ParseException: invalid token 'FROM' at test_invoke.test_parameter_named_from:3

----------------------------------------------------------------------
Ran 189 tests in 1.629s

FAILED (errors=2)
```

**Comment by keithbrown** [comment]
I have also found another problem using the 8b7a217 suggested fix, nested for loops throw off first/last calculation.  

Example A:

```
    .for each element in path
      .assign count = count + 1
      .if(last path)
        .assign child_element = element
      .else
        .for each e in inner_path
          .assign innerCount = innerCount + 1
        .end for
        .select any ei from instances of EI where ( selected.Name == element.Name )
        .select one table related by ei->T[R4]
        .if(first path)
          .assign parent_element = element
          .assign parent_table = table
          .print "SKB - assigned parent table to ${parent_table.Name} "
        .end if
      .end if
  .end for
```

Example A fails the calculation of `.if( first path)`.  This never returns true and it should eventually return true.

Example B:

```
    .for each element in path
      .assign count = count + 1
      .if(last path)
        .assign child_element = element
      .else
        .select any ei from instances of EI where ( selected.Name == element.Name )
        .select one table related by ei->T[R4]
        .if(first path)
          .assign parent_element = element
          .assign parent_table = table
          .print "SKB - assigned parent table to ${parent_table.Name} "
        .end if
        .for each e in inner_path
          .assign innerCount = innerCount + 1
        .end for
      .end if
  .end for
```

On the other hand, if I move the `.if(first path)` test before the nested for-loop, the test will return true at the proper point and my code works.

The nested for is causing a problem.

**Comment by john-tornblom** [comment]
The parse error you get is due to an old cached parse table you got locally. I changed the grammar the other day... The tables are generally generated by `python setup build` at install time.

So, just do:

```
rm rsl/__rsl*
python setup build
```

**Comment by john-tornblom** [comment]
The following code seems to work for me, what am I missing? 

``` python
    def test_first_operator_in_nested_loops(self):
        self.metamodel.define_class('A', [('ID', 'integer')])
        self.metamodel.define_class('B', [('ID', 'integer')])
        self.metamodel.define_class('C', [('ID', 'integer')])

        text = '''
          .select any child_element from instances of A
          .select any parent_element from instances of A

          .select many path from instances of A
          .select many inner_path from instances of B where (false)
          .select many parent_element from instances of B where (false)
          .assign count = 0
          .assign innerCount = 0
          .for each element in path
            .assign count = count + 1
            .if(last path)
              .assign child_element = element
            .else
              .for each e in inner_path
                .assign innerCount = innerCount + 1
              .end for
              .select any ei from instances of C where ( selected.ID == element.ID )
              .if(first path)
                .assign parent_element = element
                .exit 1
              .end if
            .end if
          .end for
          .exit 0
        '''

        self.metamodel.new('A', ID=1);
        self.metamodel.new('A', ID=2);
        self.metamodel.new('A', ID=3);

        self.metamodel.new('B', ID=6);
        self.metamodel.new('B', ID=7);
        self.metamodel.new('B', ID=8);

        self.metamodel.new('C', ID=1);
        self.metamodel.new('C', ID=6);

        rc = self.eval_text(text)
        self.assertEqual(1, rc)
```

**Comment by keithbrown** [comment]
Incomplete example pseudo-code on my part.  This will cause the failure:

``` python
    def test_first_operator_in_nested_loops(self):
        self.metamodel.define_class('A', [('ID', 'integer')])
        self.metamodel.define_class('C', [('ID', 'integer')])

        text = '''
          .select any child_element from instances of A
          .select any parent_element from instances of A

          .select many path from instances of A
          .assign inner_path = path
          .assign count = 0
          .assign innerCount = 0
          .for each element in path
            .assign count = count + 1
            .if(last path)
              .assign child_element = element
            .else
              .for each e in inner_path
                .assign innerCount = innerCount + 1
              .end for
              .select any ei from instances of C where ( selected.ID == element.ID )
              .if(first path)
                .assign parent_element = element
                .exit 1
              .end if
            .end if
          .end for
          .exit 0
        '''

        self.metamodel.new('A', ID=1);
        self.metamodel.new('A', ID=2);
        self.metamodel.new('A', ID=3);

        self.metamodel.new('C', ID=1);
        self.metamodel.new('C', ID=6);

        rc = self.eval_text(text)
        self.assertEqual(1, rc)
```

Note that I changed `inner_path` to use the same set of A instances rather than a new set of B instances.

**Comment by john-tornblom** [comment]
Ah, you iterate over the **same** set, just with two different names. The assignment `.assign inner_path = path` won't do a copy in pyrsl, inner_path and path points at the same set. 

To obtain two distinct sets, one can perform the same select query twice, e.g.
    `.select many inner_path from instances of A`

**Comment by john-tornblom** [comment]
Its an easy fix, but not sure if its worth it. Overall performance will decrease if sets are copied.

``` diff
diff --git a/rsl/eval.py b/rsl/eval.py
index 56562ce..f68e3ea 100644
--- a/rsl/eval.py
+++ b/rsl/eval.py
@@ -157,9 +157,13 @@ class EvalWalker(xtuml.tools.Walker):

     def accept_VariableAssignmentNode(self, node):
         assert isinstance(node, ast.VariableAssignmentNode)
-        
-        setter = lambda val: self.symtab.install_symbol(node.name, val)

+        def setter(val):
+            if isinstance(val, xtuml.QuerySet):
+                val = xtuml.QuerySet(val)
+                
+            self.symtab.install_symbol(node.name, val)
+        
         return property(fset=setter)
```

**Comment by john-tornblom** [comment]
Regarding the comments on the accuracy of the test cases, I don't want test cases to assume that instances are stored in the same order as they are created. But I think https://github.com/john-tornblom/pyrsl/commit/03932bffc8912bb62a01aae98ec6b32f60350cae addresses your concerns sufficiently.

**Comment by john-tornblom** [comment]
@keithbrown, @cortlandstarrett , do you think https://github.com/xtuml/pyrsl/commit/8b7a2171f0ba329143289d98da8653ea889c0b7e and https://github.com/xtuml/pyrsl/commit/03932bffc8912bb62a01aae98ec6b32f60350cae addresses the issue sufficiently? I don't think its worth doing copy on assignment for sets just to support this. Its easier to just create a second query when this kind of behaviour is needed. I think its the grammar that is the real problem. the first/not_first etc should really be a binary operation, e.g. if (inst first in inst_set).

**Comment by john-tornblom** [comment]
I'm closing this issue due to inactivity. Reopen if needed.
