### ISSUE TITLE
Foreign characters cause failure in python3

### ISSUE THREAD

**Issue by cortlandstarrett** [xtuml/pyrsl#3]
The following line is in a marking file that gets included during gen_erate translation.

.// 以下 does not exit になるやつ

On Linux, gen_erate deals with this just fine.  On Windows, I see a character mapping error.

<pre>

q.main.arc: 19:  ERROR:  'charmap' codec can't decode byte 0x81 in position 26: character maps to <undefined>
Traceback  (most recent call last):
    File "C:\Users\cort\workspace2016_2\MicrowaveOven\gen\code_generation\arc\sys.arc", line 73
    File "C:\Users\cort\workspace2016_2\MicrowaveOven\gen\code_generation\arc\q.main.arc", line 19
'charmap' codec can't decode byte 0x81 in position 26: character maps to <undefined>

</pre>

Do you have advice?

**Comment by cortlandstarrett** [comment]
http://stackoverflow.com/questions/9233027/unicodedecodeerror-charmap-codec-cant-decode-byte-x-in-position-y-character

**Comment by cortlandstarrett** [comment]
The encoding in the example above seems to be cp932.

**Comment by cortlandstarrett** [comment]
I am learning way to recognize the encoding, coerce it, etc.  Nothing I have found looks clean, yet.

I wonder about discarding comments early on somehow.

**Comment by cortlandstarrett** [comment]
narrowing further
The problem happens only with the Windows-packaged gen_erate.exe.  With Python installed, the encoding seems to be fine.

**Comment by cortlandstarrett** [comment]
Notice the simple command line.  The datatype.mark file consists of just 1 line (having the line shown in a previous comment).

<pre>
gen_erate.exe -arch datatype.mark
Traceback (most recent call last):
  File "gen_erate.py", line 255, in <module>
  File "gen_erate.py", line 236, in main
  File "C:\projects\pyrsl\rsl\parse.py", line 1352, in parse_file
  File "C:\projects\pyrsl\rsl\parse.py", line 137, in filename_input
  File "C:\Python34\lib\encodings\cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 26: character maps to &lt;undefined&gt;
</pre>

**Comment by cortlandstarrett** [comment]
A few more data points:
Test case now has 2 lines to better see successful execution:

.// 以下 does not exit になるやつ
.print "hello"

From the Cygwin command line, I run:
gen_erate.exe -arch datatype.mark  <--- fails
gen_erate.pyz -arch datatype.mark  <--- succeeds (and prints hello)

**Comment by john-tornblom** [comment]
could you try to change the mode in which files are opened for parsing to binary mode:

In rsl/parse.py

```
    def filename_input(self, filename):
        with open(filename, 'rb') as f:
            return self.text_input(f.read(), filename)
```

**Comment by cortlandstarrett** [comment]
I will do this.  I am still setting up my gen_erate.exe packaging environment.

**Comment by cortlandstarrett** [comment]
This has been working.  And the input archetypes clearly have wide characters.

However, I ran into one more case:
fx_domain_debug_utility.arc: 676:  INFO:  File '....\myGenDir\3020_src\IOTsc_dbg_utility_full.c' CREATED
fx_domain_debug_utility.arc: 676:  ERROR:  'charmap' codec can't encode characters in position 4751-4753: character maps to <undefined>
Traceback  (most recent call last):
    File "Z:\gitf\fxmc\models\IOTsc\gen\code_generation\arc\sys.arc", line 411
    File "Z:\gitf\fxmc\models\IOTsc\gen\code_generation\arc\fx_domain_debug_utility.arc", line 676
'charmap' codec can't encode characters in position 4751-4753: character maps to <undefined>
Code generation complete.
Sun Mar 20 05:30:47 2016

I wonder if there is another place where encoding needs to be coerced or forced?  (in the emit operation)?

**Comment by john-tornblom** [comment]
Possibly. I've temporarily enabled the python stack trace on a feature branch at https://github.com/john-tornblom/pyrsl/tree/win32_py34_encoding This version should reveal more information on where the exception is encountered in the python code.
You'll see two stack traces printed to stdout, one with the rsl stack trace, and one from the python stack trace.

A binary is available at https://ci.appveyor.com/api/buildjobs/7ypg64cxpghrudiu/artifacts/dist/gen_erate.exe

**Comment by cortlandstarrett** [comment]
...re-running my test case now.  I will report in about 5 hours.  :)

**Comment by cortlandstarrett** [comment]
fx_domain_debug_utility.arc: 676:  INFO:  File '....\myGenDir\3020_src\IOTsc_dbg_utility_full.c' REPLACED
fx_domain_debug_utility.arc: 676:  ERROR:  'charmap' codec can't encode characters in position 4751-4753: character maps to <undefined>
Traceback  (most recent call last):
    File "Z:\gitf\fxmc\models\IOTsc\gen\code_generation\arc\sys.arc", line 411
    File "Z:\gitf\fxmc\models\IOTsc\gen\code_generation\arc\fx_domain_debug_utility.arc", line 676
Traceback (most recent call last):
  File "C:\projects\pyrsl\rsl\eval.py", line 45, in accept
  File "C:\Python34\lib\site-packages\xtuml\tools.py", line 65, in accept
  File "C:\projects\pyrsl\rsl\eval.py", line 360, in accept_EmitNode
  File "C:\projects\pyrsl\rsl\runtime.py", line 249, in emit_buffer
  File "C:\Python34\lib\encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 4751-4753: character maps to <undefined>

'charmap' codec can't encode characters in position 4751-4753: character maps to <undefined>
Code generation complete.
Sun Mar 20 14:52:13 2016

**Comment by john-tornblom** [comment]
Yepp, the emit method compares with existing data on disk, and thus may read non-utf8.

Updated binary available at https://ci.appveyor.com/api/buildjobs/409tpah04nvt2a6w/artifacts/dist/gen_erate.exe

**Comment by cortlandstarrett** [comment]
O.K.  Thanks.
downloading, will have more results soon.

**Comment by cortlandstarrett** [comment]
## Hmm, it seems to have behaved the same.

fx_domain_debug_utility.arc: 676:  INFO:  File '....\myGenDir\3020_src\IOTsc_dbg_utility_full.c' REPLACED
fx_domain_debug_utility.arc: 676:  ERROR:  'charmap' codec can't encode characters in position 4751-4753: character maps to <undefined>
Traceback  (most recent call last):
    File "Z:\gitf\fxmc\models\IOTsc\gen\code_generation\arc\sys.arc", line 411
    File "Z:\gitf\fxmc\models\IOTsc\gen\code_generation\arc\fx_domain_debug_utility.arc", line 676
Traceback (most recent call last):
  File "C:\projects\pyrsl\rsl\eval.py", line 45, in accept
  File "C:\Python34\lib\site-packages\xtuml\tools.py", line 65, in accept
  File "C:\projects\pyrsl\rsl\eval.py", line 360, in accept_EmitNode
  File "C:\projects\pyrsl\rsl\runtime.py", line 249, in emit_buffer
  File "C:\Python34\lib\encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 4751-4753: character maps to <undefined>

'charmap' codec can't encode characters in position 4751-4753: character maps to <undefined>
Code generation complete.
Sun Mar 20 20:22:32 2016

My gen_erate.exe binary has 5502877 bytes.

**Comment by john-tornblom** [comment]
Okey, I've gone over this again and added some test cases. 

binary available at https://ci.appveyor.com/api/buildjobs/x048olbvvy722ewq/artifacts/dist/gen_erate.exe

Note that unrecognized character sequences are replaced with �. For example, if the script is designed to emit 日本語, and is encoded as cp932, the resulting text file will be encoded as utf8, and contain ���{��

**Comment by cortlandstarrett** [comment]
...got it.  Will report results within a few hours.

**Comment by cortlandstarrett** [comment]
Test passed.

sys.arc: 414:  INFO:  ending Mon Mar 21 22:56:58 2016
Code generation complete.
Mon Mar 21 22:57:02 2016

**Comment by john-tornblom** [comment]
Unfortunately, the change I made to get the last exe file to work  (based on python 3.4) causes other problems when using pypy, and some older python2 releases. python3 treat strings very differently than python2 used to do. I've now reverted back the change, but switched to python2 for the exe file.

Could you confirm the new exe still works? See https://ci.appveyor.com/api/buildjobs/gg1ad20hut5dg2fg/artifacts/dist/gen_erate.exe

**Comment by cortlandstarrett** [comment]
I will run a test case tonight.

**Comment by cortlandstarrett** [comment]
Test passed.
