### ISSUE TITLE
Error running 0.5.0 gen_erate.pyz

### ISSUE THREAD

**Issue by keithbrown** [xtuml/pyrsl#4]
I gen'd MicrowaveOven successfully using an older version, then I dropped in the new version and I see the following errors in the build console:

```
Thu Apr  7 14:06:52 2016
xtumlmc_build -home /tmp/BridgePoint/eclipse/plugins/org.xtuml.bp.mc.c.source_5.3.2/ -l3s -e -d code_generation -O ../../src/
Upgrading translation workspace:  code_generation
Enabling detection of empty handles for component(s) *.
Action statement tracing enabled for component MicrowaveOven.
Enabling state transition tracing for component(s) *.
Function TestSequence1 marked as initialization function.
Function DefineOven marked as initialization function.
Analyzing model and making optimizations....
Self event queue needed.
Instance event queue needed.
7 attributes read
7 attributes written
translating control statements
translating other statements
rolling up statements into action bodies
done translating statements
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/BridgePoint/eclipse/plugins/org.xtuml.bp.mc.c.source_5.3.2/mc3020/bin/gen_erate.pyz/__main__.py", line 2, in <module>
  File "/tmp/BridgePoint/eclipse/plugins/org.xtuml.bp.mc.c.source_5.3.2/mc3020/bin/gen_erate.pyz/rsl/gen_erate.py", line 232, in main
  File "/tmp/BridgePoint/eclipse/plugins/org.xtuml.bp.mc.c.source_5.3.2/mc3020/bin/gen_erate.pyz/xtuml/load.py", line 283, in populate
  File "/tmp/BridgePoint/eclipse/plugins/org.xtuml.bp.mc.c.source_5.3.2/mc3020/bin/gen_erate.pyz/xtuml/load.py", line 271, in populate_instances
  File "/tmp/BridgePoint/eclipse/plugins/org.xtuml.bp.mc.c.source_5.3.2/mc3020/bin/gen_erate.pyz/xtuml/load.py", line 73, in deserialize_value
ValueError: invalid literal for int() with base 10: "'Time::current_date'"
Code generation complete.
Thu Apr  7 14:06:52 2016
```

**Comment by john-tornblom** [comment]
looks like a schema/instance mismatch. The schema expect a unique_id, while the insert into statement provide a string (with the value Time::current_date)

**Comment by keithbrown** [comment]
Thank you for the input.  Definitely a schema problem.  It's related to us moving to the new schema dumper.  Details here: https://support.onefact.net/issues/8425
